"""
ProtoPNet Dataset Augmentation Pipeline
-----------------------------------------
Generates augmented copies of training images to increase dataset size
and improve model robustness. Val and test sets are never touched.

Augmentations applied (matching the ProtoPNet research workflow):
  - Random resized crop    (scale 0.7–1.0, output 224×224)
  - Random horizontal flip (p=0.5)
  - Random vertical flip   (p=0.3)
  - Random rotation        (±30 degrees)
  - Colour jitter          (brightness, contrast, saturation, hue)
  - Gaussian blur          (p=0.2)

Install dependencies:
  pip install Pillow tqdm numpy torchvision torch
"""

import logging
import random
import shutil
import sys
from pathlib import Path

import numpy as np
from PIL import Image
from tqdm import tqdm
import torchvision.transforms as T


# ---------------------------------------------------------------------------
# Configuration — edit these values before running
# ---------------------------------------------------------------------------

CONFIG = {
    # Input: the train/ folder produced by preprocess.py
    # Expected structure: TRAIN_DIR/<class_name>/<image_files>
    "TRAIN_DIR": "./Dataset/plantwild/train",

    # Where to write augmented images.
    # "same" → saves augmented files into the same class folders as the originals
    #          (recommended — PyTorch ImageFolder sees originals + augmented together)
    # any path → copies originals there and writes augmented files alongside them
    "OUTPUT_MODE": "same",

    # Only used when OUTPUT_MODE is not "same"
    "OUTPUT_DIR": "./Dataset/plantwild_augmented/train",

    # Augmented copies to generate per original image.
    # 3 means each image produces 3 new variants → effective dataset size is ~4×.
    "COPIES_PER_IMAGE": 3,

    # Minority class boost: classes with fewer than MIN_SAMPLES_FOR_BOOST images
    # get BOOST_COPIES_PER_IMAGE copies instead of COPIES_PER_IMAGE.
    "ENABLE_BOOST": True,
    "MIN_SAMPLES_FOR_BOOST": 50,
    "BOOST_COPIES_PER_IMAGE": 7,

    # Augmentation parameters
    "FLIP_H_PROB":      0.5,
    "FLIP_V_PROB":      0.3,
    "ROTATION_DEGREES": 30,
    "COLOR_BRIGHTNESS": 0.3,
    "COLOR_CONTRAST":   0.3,
    "COLOR_SATURATION": 0.2,
    "COLOR_HUE":        0.05,   # slight hue shift — safe default not in original spec
    "CROP_SCALE_MIN":   0.7,
    "CROP_SCALE_MAX":   1.0,
    "BLUR_PROB":        0.2,
    "BLUR_KERNEL_MIN":  3,      # must be odd
    "BLUR_KERNEL_MAX":  5,      # must be odd
    "OUTPUT_IMG_SIZE":  (224, 224),

    # Output file settings
    "SAVE_FORMAT":  "JPEG",
    "SAVE_QUALITY": 95,
    "AUG_PREFIX":   "aug",      # augmented filenames start with this prefix

    "RANDOM_SEED":   42,
    "LOG_FILE":      "augmentation.log",
    "SUPPORTED_EXT": {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".webp"},
}


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
    handlers=[
        logging.FileHandler(CONFIG["LOG_FILE"], mode="w", encoding="utf-8"),
        logging.StreamHandler(
            stream=open(sys.stdout.fileno(), mode="w", encoding="utf-8", closefd=False)
        ),
    ],
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Step 1 — Scan the training directory
# ---------------------------------------------------------------------------

def scan_train_dir(train_dir: Path) -> dict[str, list[Path]]:
    """
    Collect original image paths grouped by class, skipping any files
    that were already generated by a previous augmentation run (identified
    by the AUG_PREFIX in their filename).

    Returns a dict mapping class name → list of original image Paths.
    """
    log.info(f"Scanning training directory: {train_dir}")

    if not train_dir.exists():
        log.error(f"TRAIN_DIR not found: {train_dir}")
        sys.exit(1)

    class_dirs = sorted(d for d in train_dir.iterdir() if d.is_dir())
    if not class_dirs:
        log.error("No class subfolders found in TRAIN_DIR.")
        sys.exit(1)

    valid_extensions = CONFIG["SUPPORTED_EXT"]
    aug_prefix = CONFIG["AUG_PREFIX"]
    class_to_files: dict[str, list[Path]] = {}

    for class_dir in tqdm(class_dirs, desc="Scanning classes"):
        originals = [
            f for f in class_dir.iterdir()
            if f.suffix.lower() in valid_extensions
            and not f.stem.startswith(aug_prefix)
        ]
        if originals:
            class_to_files[class_dir.name] = originals

    total = sum(len(v) for v in class_to_files.values())
    log.info(f"Found {total} original images across {len(class_to_files)} classes.")
    return class_to_files


# ---------------------------------------------------------------------------
# Step 2 — Build the augmentation pipeline
# ---------------------------------------------------------------------------

def build_augmentation_pipeline() -> T.Compose:
    """
    Compose the torchvision transforms used to generate each augmented image.

    The order is intentional:
      1. Random crop  — forces the model to focus on disease regions, not backgrounds
      2. Flips        — adds viewpoint invariance
      3. Rotation     — simulates different leaf angles in field photos
      4. Colour jitter — handles the wide lighting variation in PlantWild images
      5. Gaussian blur — accounts for varying camera quality and focus

    Note: ToTensor and Normalize are deliberately excluded. Images are saved
    as JPEG files here; normalisation is handled by the DataLoader at training time.
    """
    cfg = CONFIG

    pipeline = T.Compose([
        # 1. Random crop — scale 0.7–1.0, output resized to target size
        T.RandomResizedCrop(
            size=cfg["OUTPUT_IMG_SIZE"],
            scale=(cfg["CROP_SCALE_MIN"], cfg["CROP_SCALE_MAX"]),
            ratio=(0.75, 1.333),
            interpolation=T.InterpolationMode.LANCZOS,
        ),

        # 2. Horizontal flip (p=0.5)
        T.RandomHorizontalFlip(p=cfg["FLIP_H_PROB"]),

        # 3. Vertical flip (p=0.3) — valid for overhead field photography
        T.RandomVerticalFlip(p=cfg["FLIP_V_PROB"]),

        # 4. Rotation ±30°, black-padded edges
        T.RandomRotation(
            degrees=cfg["ROTATION_DEGREES"],
            interpolation=T.InterpolationMode.BILINEAR,
            fill=0,
        ),

        # 5. Colour jitter — critical for PlantWild's wide lighting variation
        T.ColorJitter(
            brightness=cfg["COLOR_BRIGHTNESS"],
            contrast=cfg["COLOR_CONTRAST"],
            saturation=cfg["COLOR_SATURATION"],
            hue=cfg["COLOR_HUE"],
        ),

        # 6. Occasional Gaussian blur to simulate focus variation
        T.RandomApply([
            T.GaussianBlur(
                kernel_size=cfg["BLUR_KERNEL_MAX"],
                sigma=(0.1, 2.0),
            )
        ], p=cfg["BLUR_PROB"]),
    ])

    log.info("Augmentation pipeline:")
    log.info(f"  Random crop     scale={cfg['CROP_SCALE_MIN']}–{cfg['CROP_SCALE_MAX']}, output={cfg['OUTPUT_IMG_SIZE']}")
    log.info(f"  Horizontal flip p={cfg['FLIP_H_PROB']}")
    log.info(f"  Vertical flip   p={cfg['FLIP_V_PROB']}")
    log.info(f"  Rotation        ±{cfg['ROTATION_DEGREES']}°")
    log.info(f"  Colour jitter   brightness={cfg['COLOR_BRIGHTNESS']}, contrast={cfg['COLOR_CONTRAST']}, saturation={cfg['COLOR_SATURATION']}")
    log.info(f"  Gaussian blur   p={cfg['BLUR_PROB']}, kernel={cfg['BLUR_KERNEL_MAX']}")

    return pipeline


# ---------------------------------------------------------------------------
# Step 3 — Decide how many copies to generate per class
# ---------------------------------------------------------------------------

def compute_copies_per_class(class_to_files: dict) -> dict[str, int]:
    """
    Return a mapping of class name → number of augmented copies per original image.

    Classes with fewer than MIN_SAMPLES_FOR_BOOST images receive a higher copy
    count to help them catch up with larger classes.
    """
    copies_map: dict[str, int] = {}
    boosted: list[tuple[str, int]] = []

    for cls, files in class_to_files.items():
        n = len(files)
        if CONFIG["ENABLE_BOOST"] and n < CONFIG["MIN_SAMPLES_FOR_BOOST"]:
            copies_map[cls] = CONFIG["BOOST_COPIES_PER_IMAGE"]
            boosted.append((cls, n))
        else:
            copies_map[cls] = CONFIG["COPIES_PER_IMAGE"]

    if boosted:
        log.info(
            f"Boost applied to {len(boosted)} minority classes "
            f"(< {CONFIG['MIN_SAMPLES_FOR_BOOST']} images):"
        )
        for cls, n in sorted(boosted, key=lambda x: x[1]):
            log.info(f"  {cls:<45} original={n:>4}  copies={CONFIG['BOOST_COPIES_PER_IMAGE']}")

    return copies_map


# ---------------------------------------------------------------------------
# Step 4 — Resolve where augmented files should be written
# ---------------------------------------------------------------------------

def _output_dir_for_class(class_name: str, train_dir: Path) -> Path:
    """
    Return the folder where augmented images for a given class should be saved.
    In "same" mode this is the existing class folder; otherwise a new path is created.
    """
    if CONFIG["OUTPUT_MODE"] == "same":
        return train_dir / class_name

    out = Path(CONFIG["OUTPUT_DIR"]) / class_name
    out.mkdir(parents=True, exist_ok=True)
    return out


def copy_originals_if_needed(class_to_files: dict, train_dir: Path) -> None:
    """
    When writing to a separate output directory, copy all original images there
    first so the augmented folder contains both originals and new variants.
    Skipped entirely in "same" mode.
    """
    if CONFIG["OUTPUT_MODE"] == "same":
        return

    log.info("Copying originals to output directory...")
    for cls, files in tqdm(class_to_files.items(), desc="Copying originals"):
        out_dir = Path(CONFIG["OUTPUT_DIR"]) / cls
        out_dir.mkdir(parents=True, exist_ok=True)
        for f in files:
            dest = out_dir / f.name
            if not dest.exists():
                shutil.copy2(f, dest)


# ---------------------------------------------------------------------------
# Step 5 — Run augmentation
# ---------------------------------------------------------------------------

def augment_dataset(
    class_to_files: dict,
    pipeline: T.Compose,
    copies_map: dict[str, int],
    train_dir: Path,
) -> dict[str, dict]:
    """
    Generate augmented images for every class and save them alongside the originals.

    Each augmented file is named:  aug_<original_stem>_<index>.jpg

    Returns per-class stats: {class_name: {original, generated, total}}
    """
    save_format = CONFIG["SAVE_FORMAT"]
    save_quality = CONFIG["SAVE_QUALITY"]
    prefix = CONFIG["AUG_PREFIX"]
    stats: dict[str, dict] = {}
    n_errors = 0

    for cls, files in class_to_files.items():
        n_copies = copies_map[cls]
        out_dir = _output_dir_for_class(cls, train_dir)
        n_generated = 0

        for src_path in tqdm(files, desc=f"{cls[:40]:<40} (×{n_copies})", leave=False):
            try:
                with Image.open(src_path) as img:
                    img = img.convert("RGB")

                for i in range(n_copies):
                    aug_img = pipeline(img)
                    out_name = f"{prefix}_{src_path.stem}_{i:03d}.jpg"
                    aug_img.save(out_dir / out_name, save_format, quality=save_quality)
                    n_generated += 1

            except Exception as exc:
                n_errors += 1
                log.warning(f"Skipped (error): {src_path} — {exc}")

        stats[cls] = {
            "original":  len(files),
            "generated": n_generated,
            "total":     len(files) + n_generated,
        }

    if n_errors:
        log.warning(f"{n_errors} image(s) skipped due to errors.")

    return stats


# ---------------------------------------------------------------------------
# Step 6 — Write summary report
# ---------------------------------------------------------------------------

def write_summary(stats: dict, train_dir: Path) -> None:
    """Save a plain-text augmentation summary and print it to the terminal."""
    total_original  = sum(v["original"]  for v in stats.values())
    total_generated = sum(v["generated"] for v in stats.values())
    total_final     = sum(v["total"]     for v in stats.values())

    lines = [
        "=" * 65,
        "AUGMENTATION SUMMARY",
        "=" * 65,
        f"Train directory     : {CONFIG['TRAIN_DIR']}",
        f"Output mode         : {CONFIG['OUTPUT_MODE']}",
        f"Copies per image    : {CONFIG['COPIES_PER_IMAGE']} "
        f"(boosted classes: {CONFIG['BOOST_COPIES_PER_IMAGE']})",
        f"Boost threshold     : < {CONFIG['MIN_SAMPLES_FOR_BOOST']} original images",
        "",
        f"Total classes       : {len(stats)}",
        f"Original images     : {total_original:>7}",
        f"Generated images    : {total_generated:>7}",
        f"Final train total   : {total_final:>7}",
        f"Effective multiplier: {total_final / max(total_original, 1):.2f}×",
        "",
        f"{'Class':<45} {'Orig':>5} {'Gen':>6} {'Total':>6}",
        "-" * 65,
    ]

    for cls, v in sorted(stats.items(), key=lambda x: x[1]["total"], reverse=True):
        lines.append(
            f"  {cls:<43} {v['original']:>5} {v['generated']:>6} {v['total']:>6}"
        )

    lines.append("=" * 65)
    summary = "\n".join(lines)

    if CONFIG["OUTPUT_MODE"] == "same":
        summary_path = train_dir.parent / "augmentation_summary.txt"
    else:
        summary_path = Path(CONFIG["OUTPUT_DIR"]).parent / "augmentation_summary.txt"

    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(summary)

    log.info(f"Summary written to: {summary_path}")
    print("\n" + summary)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    random.seed(CONFIG["RANDOM_SEED"])
    np.random.seed(CONFIG["RANDOM_SEED"])

    train_dir = Path(CONFIG["TRAIN_DIR"])

    log.info("=" * 65)
    log.info("  ProtoPNet Augmentation Pipeline")
    log.info("=" * 65)
    log.info(f"Train dir        : {train_dir}")
    log.info(f"Copies per image : {CONFIG['COPIES_PER_IMAGE']}")
    log.info(
        f"Boost enabled    : {CONFIG['ENABLE_BOOST']} "
        f"(threshold < {CONFIG['MIN_SAMPLES_FOR_BOOST']}, copies={CONFIG['BOOST_COPIES_PER_IMAGE']})"
    )

    class_to_files = scan_train_dir(train_dir)
    pipeline       = build_augmentation_pipeline()
    copies_map     = compute_copies_per_class(class_to_files)

    copy_originals_if_needed(class_to_files, train_dir)

    log.info("Starting augmentation...")
    stats = augment_dataset(class_to_files, pipeline, copies_map, train_dir)

    write_summary(stats, train_dir)
    log.info("Augmentation complete.")


if __name__ == "__main__":
    main()
